Repository framgia/pj_sim-sunbnb, pull requests merged in 2023-08, with the labels that each got.

#12 PJ_SIM_SUNBNB_2023-11 [FE] Home Page Components Banner
  fe/package-lock.json
  fe/package.json
  fe/src/App.vue
  fe/src/components/DatePicker.vue
  fe/src/components/HomepageBanner.vue
Labels: For Review

#22 Hotfix/Fix-routes
  fe/src/App.vue
  fe/src/pages/AllComponents.vue
  fe/src/pages/HelloWorld.vue
  fe/src/router/index.js
Labels: For Review

#13 Feature/PJ_SIM_SUNBNB_2023-13-[FE] Home Page Cities Component
  fe/src/components/Cities/CityCard.vue
  fe/src/pages/HelloWorld.vue
  fe/src/pages/RegistrationView.vue
  fe/src/router/index.js
  fe/src/utilities/dummy/Cities.json
Labels: For Review

#16 PJ_SIM_SUNBNB_2023-22 [FE] Filter Component
  fe/src/assets/css/global.css
  fe/src/components/HomepageBanner.vue
  fe/src/components/filter/AmenitiesCheckbox.vue
  fe/src/components/filter/PriceSlider.vue
  fe/src/components/filter/RoomCheckbox.vue
  fe/src/components/filter/ShowFilter.vue
  fe/src/components/filter/index.js
  fe/src/pages/AllComponents.vue
Labels: For Review, high priority

#14 Feature/PJ_SIM_SUNBNB_2023-17-[FE] Tab Component
  fe/src/components/Tab/HostTab.vue
  fe/src/components/Tab/ListingTab.vue
  fe/src/pages/AllComponents.vue
  fe/src/pages/HelloWorld.vue
  fe/src/pages/RegistrationView.vue
  fe/src/router/index.js
Labels: For Review, high priority

#18 PJ_SIM_SUNBNB_2023-15 [FE] Listing Item Component
  fe/src/components/Listings.vue
Labels: For Review

#26 PJ_SIM_SUNBNB_2023-12 [FE] Home Page Card Component
  fe/src/components/ListingCard.vue
  fe/src/pages/AllComponents.vue
  fe/src/utilities/dummy/ListingData.json
Labels: For Review, high priority

#28 PJ_SIM_SUNBNB_2023-19 [FE] Edit Profile Page
  fe/src/components/Navbar/NavbarProfile.vue
  fe/src/pages/EditProfile.vue
  fe/src/router/index.js
Labels: For Review

#29 Hotfix/recoverRegistrationPage
  fe/src/components/Cities/CityCard.vue
  fe/src/pages/RegistrationView.vue
  fe/src/router/index.js
  fe/src/utilities/dummy/Cities.json
Labels: For Review

#19 PJ_SIM_SUNBNB_2023-20 [FE] Add New Listing Markup Page
  fe/src/components/Tab/HostTab.vue
  fe/src/components/Tab/ListingTab.vue
  fe/src/pages/AddNewListingView.vue
  fe/src/router/index.js
Labels: For Review

#32 Hotfix/Registration Page View
  fe/package-lock.json
  fe/package.json
  fe/src/pages/RegistrationView.vue
Labels: bug, For Review

#25 PJ_SIM_SUNBNB_2023-14 [FE] Home Page markup
  fe/src/components/Cities/CityCard.vue
  fe/src/components/HomepageBanner.vue
  fe/src/components/Navbar/NavigationBar.vue
  fe/src/pages/HomeView.vue
  fe/src/router/index.js
  fe/src/utilities/dummy/Cities.json
Labels: For Review

#30 PJ_SIM_SUNBNB_2023-15 [FE] Listing Item Component
  fe/src/components/ListingCard.vue
  fe/src/components/Listings.vue
  fe/src/components/ListingsList.vue
  fe/src/pages/AllComponents.vue
  fe/src/utilities/dummy/ListingData.json
Labels: Approved, For Review, high priority

#27 PJ_SIM_SUNBNB_2023-25 [FE] User Profile
  fe/src/components/Navbar/NavbarProfile.vue
  fe/src/components/Review/ReviewHost.vue
  fe/src/components/Review/ReviewRoom.vue
  fe/src/components/Tab/HostTab.vue
  fe/src/pages/ClientViewProfile.vue
  fe/src/pages/HostViewProfile.vue
  fe/src/router/index.js
  fe/src/utilities/dummy/User.json
Labels: For Review

#31 PJ_SIM_SUNBNB_2023-21-FE-Search-Page
  fe/src/components/ListingsList.vue
  fe/src/components/filter/ShowFilter.vue
  fe/src/pages/AllComponents.vue
  fe/src/pages/HomeView.vue
  fe/src/pages/SearchView.vue
  fe/src/router/index.js
  fe/src/utilities/dummy/ListingData.json
Labels: For Review

#33 Hotfix/Fix Route Names
  fe/src/router/index.js
Labels: For Review, high priority

#20 PJ_SIM_SUNBNB_2023-24 [FE] Listing Page or Room Page
  fe/package-lock.json
  fe/public/bathtub.png
  fe/public/bed.png
  fe/public/condo.png
  fe/public/hotel.png
  fe/public/house.png
  fe/public/person.png
  fe/src/App.vue
  fe/src/components/Review/ReviewRoom.vue
  fe/src/pages/RoomPage.vue
  fe/src/router/index.js
Labels: For Review

#34 Hotfix/Fix-Input-Height
  fe/src/components/HomepageBanner.vue
  fe/src/components/Navbar/NavbarProfile.vue
Labels: For Review
